export const provincias = [
  'Bengo',
  'Benguela',
  'Bié',
  'Cabinda',
  'Cuando Cubango',
  'Cuanza Norte',
  'Cuanza Sul',
  'Cunene',
  'Huambo',
  'Huíla',
  'Luanda',
  'Lunda Norte',
  'Lunda Sul',
  'Malanje',
  'Moxico',
  'Namibe',
  'Uíge',
  'Zaire',
];

export const nacionalidades = [
  'Alemã',
  'Americana',
  'Angolana',
  'Argentina',
  'Australiana',
  'Austríaca',
  'Belga',
  'Brasileira',
  'Britânica',
  'Canadense',
  'Chinesa',
  'Dinamarquesa',
  'Emiradense',
  'Egípcia',
  'Espanhola',
  'Filipina',
  'Francesa',
  'Grega',
  'Indiana',
  'Indonésia',
  'Iraniana',
  'Israelense',
  'Italiana',
  'Japonesa',
  'Malaia',
  'Mexicana',
  'Neerlandesa',
  'Norueguesa',
  'Polonesa',
  'Portuguesa',
  'Russa',
  'Saudita',
  'Singapuriana',
  'Sueca',
  'Sul-africana',
  'Sul-coreana',
  'Suíça',
  'Tailandesa',
  'Turca',
  'Vietnamita',
  'Zambiana',
  'Zimbabuana',
  'Outra',
];

export const municipiosPorProvincia = {
  'Bengo': ['Ambriz', 'Dande', 'Dembos', 'Nambuangongo'],
  'Benguela': [
    'Baía Farta',
    'Benguela',
    'Bocoio',
    'Caimbambo',
    'Catumbela',
    'Chongoroi',
    'Cubal',
    'Ganda',
    'Lobito',
  ],
  'Bié': [
    'Andulo',
    'Camacupa',
    'Catabola',
    'Chinguar',
    'Chitembo',
    'Cuemba',
    'Cunhinga',
    'Kuito',
    'Nharea',
  ],
  'Cabinda': ['Belize', 'Buco-Zau', 'Cabinda', 'Cacongo'],
  'Cuando Cubango': [
    'Calai',
    'Cuangar',
    'Cuchi',
    'Cuito Cuanavale',
    'Dirico',
    'Mavinga',
    'Menongue',
    'Nankova',
    'Rivungo',
  ],
  'Cuanza Norte': [
    'Ambaca',
    'Banga',
    'Bolongongo',
    'Cambambe',
    'Cazengo',
    'Golungo Alto',
    'Gonguembo',
    'Lucala',
    'Quiculungo',
    'Samba Caju',
  ],
  'Cuanza Sul': [
    'Amboim',
    'Cassongue',
    'Cela',
    'Conda',
    'Ebo',
    'Libolo',
    'Mussende',
    'Porto Amboim',
    'Quibala',
    'Seles',
    'Sumbe',
  ],
  'Cunene': ['Cahama', 'Cuanhama', 'Curoca', 'Cuvelai', 'Namacunde', 'Ombadja'],
  'Huambo': [
    'Bailundo',
    'Caála',
    'Ekunha',
    'Huambo',
    'Katchiungo',
    'Londuimbale',
    'Longonjo',
    'Mungo',
    'Tchicala-Tcholohanga',
    'Tchindjenje',
  ],
  'Huíla': [
    'Caconda',
    'Caluquembe',
    'Chiange',
    'Chibia',
    'Chicomba',
    'Chipindo',
    'Gambos',
    'Humpata',
    'Jamba',
    'Kuvango',
    'Lubango',
    'Matala',
    'Quilengues',
    'Quipungo',
  ],
  'Luanda': [
    'Belas',
    'Cacuaco',
    'Cazenga',
    'Ícolo e Bengo',
    'Quilamba Quiaxi',
    'Talatona',
    'Viana',
  ],
  'Lunda Norte': [
    'Cambulo',
    'Capenda Camulemba',
    'Caungula',
    'Chitato',
    'Cuango',
    'Cuilo',
    'Lubalo',
    'Lucapa',
    'Xá-Muteba',
  ],
  'Lunda Sul': ['Cacolo', 'Dala', 'Muconda', 'Saurimo'],
  'Malanje': [
    'Cacuso',
    'Calandula',
    'Cambundi-Catembo',
    'Cangandala',
    'Caombo',
    'Cuaba Nzoji',
    'Cunda-Dia-Baze',
    'Luquembo',
    'Malanje',
    'Marimba',
    'Massango',
    'Mucari',
    'Quela',
  ],
  'Moxico': [
    'Alto Zambeze',
    'Bundas',
    'Camanongue',
    'Léua',
    'Luau',
    'Luacano',
    'Luchazes',
    'Lumbala Nguimbo',
    'Lumeje',
    'Moxico',
  ],
  'Namibe': ['Bibala', 'Camucuio', 'Moçâmedes', 'Tômbua', 'Virei'],
  'Uíge': [
    'Alto Cauale',
    'Ambuila',
    'Bembe',
    'Buengas',
    'Bungo',
    'Damba',
    'Maquela do Zombo',
    'Milunga',
    'Mucaba',
    'Negage',
    'Puri',
    'Quimbele',
    'Quitexe',
    'Sanza Pombo',
    'Songo',
    'Uíge',
  ],
  'Zaire': ['Cuimba', 'Mbanza Congo', 'Nóqui', 'Soyo', 'Tomboco'],
};

export const classes = [
  'Creche',
  'Pré-Escolar',
  '1ª Classe',
  '2ª Classe',
  '3ª Classe',
  '4ª Classe',
  '5ª Classe',
  '6ª Classe',
  '7ª Classe',
  '8ª Classe',
  '9ª Classe',
  '10ª Classe',
  '11ª Classe',
  '12ª Classe',
  '13ª Classe',
];